<?php
declare(strict_types=1);

/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link      https://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   https://opensource.org/licenses/mit-license.php MIT License
 */
namespace App\Controller;

use Cake\Controller\Controller;
use Cake\Event\EventInterface;

/**
 * Application Controller
 *
 * Add your application-wide methods in the class below, your controllers
 * will inherit them.
 *
 * @link https://book.cakephp.org/4/en/controllers.html#the-app-controller
 */
class AppController extends Controller
{
    /**
     * Initialization hook method.
     *
     * Use this method to add common initialization code like loading components.
     *
     * e.g. `$this->loadComponent('FormProtection');`
     *
     * @return void
     */
    public function initialize(): void
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');
        $this->loadComponent('Authentication.Authentication');

        /*
         * Enable the following component for recommended CakePHP form protection settings.
         * see https://book.cakephp.org/4/en/controllers/components/form-protection.html
         */
        //$this->loadComponent('FormProtection');
    }

    function beforeRender(EventInterface $event)
    {
        parent::beforeRender($event); // TODO: Change the autogenerated stub
        if (isset($this->Authentication) && !is_null($this->Authentication->getIdentity())) {
            $user = $this->Authentication->getIdentity();
            $group = $user->groupIdentity;
            $redirectPrefix = !empty($group) ? $group['redirect'] : '';

            $userTable = $this->getTableLocator()->get('Users');
            if ($user->group_id == $userTable->getNameGroup('Auditor')) {
                if (
                    is_null($user->signature)
                    && ($this->request->getParam('controller') != 'Users'
                    && $this->request->getParam('action') != 'signature')
                ) {
                    $this->redirect(['controller' => 'Users', 'action' => 'signature']);
                }
            }
            $auth = $this->Authentication->getResult();
            if ($auth->isValid()) {
                $actualPrefix = $this->request->getParam('prefix');
                if (
                    !is_null($actualPrefix)
                    && $actualPrefix != $group['prefix']
                ) {
                    $this->Flash->error(__('No tenes permisos suficientes'));
                    $this->redirect($redirectPrefix);
                }
            }

            $this->set(compact('redirectPrefix'));
        }
    }
}
